{% set version = "0.1.2" %}

package:
  name: sphinx-thebe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-thebe/sphinx-thebe-{{ version }}.tar.gz
  sha256: 756f1dd6643f5abb491f8a27b22825b04f47e05c5d214bbb2e6b5d42b621b85e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sphinx >=3.5,<5

test:
  imports:
    - sphinx_thebe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-thebe
  summary: Integrate interactive code blocks into your documentation with Thebe and Binder.
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-thebe.readthedocs.io

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
    - conda-forge/jupyter-book
