{% set version = "0.3.1" %}

package:
  name: sphinx-thebe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-thebe/sphinx_thebe-{{ version }}.tar.gz
  sha256: 576047f45560e82f64aa5f15200b1eb094dcfe1c5b8f531a8a65bd208e25a493

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - sphinx >=4

test:
  imports:
    - sphinx_thebe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/executablebooks/sphinx-thebe
  summary: Integrate interactive code blocks into your documentation with Thebe and Binder.
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-thebe.readthedocs.io

extra:
  recipe-maintainers:
    - anirrudh
    - chrisjsewell
    - conda-forge/jupyter-book
